import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const ctx=vm.createContext({});
const modules=['dex','matchups','roster','scoring','team-scoring','traits','skills','battle'];
vm.runInContext(modules.map(n=>fs.readFileSync(new URL('../src/'+n+'.js',import.meta.url),'utf8')).join('\n;\n'),ctx);
const run=s=>vm.runInContext(s,ctx);
run(`function testSpec(name){
 const a=roster.find(a=>a.name===name),available=battleCatalogFor(a).skills.filter(s=>!s.variant).map(s=>makeBattleSkill(s,{cooldown:s.cooldown??1}));
 return{a,hp:2000,atk:a.atk,available,basic:available.find(s=>s.kind==='basic'),skills:available.filter(s=>s.kind==='skill').slice(0,2),ultimate:available.find(s=>s.kind==='ultimate'),preset:'burst'};
}
let own=[testSpec('Glacy'),testSpec('Scorchhowl')],enemy=[testSpec('Panpanta')];
`);
assert.equal(run('battleSkillCatalog.length'),14);
assert.equal(run('battleSkillCatalog.reduce((n,c)=>n+c.skills.length,0)'),89);
assert.equal(run("battleCatalogFor(roster.find(a=>a.name==='Scorchhowl')).skills.filter(s=>s.kind==='skill').length"),5);
assert.equal(run("makeBattleSkill(battleSkillCatalog[0].skills[0]).cooldown"),null);
assert.equal(run("makeBattleSkill(battleSkillCatalog[0].skills[0],{cooldown:4,element:0,range:'Pound'}).cooldown"),4);
assert.equal(run("makeBattleSkill(battleSkillCatalog[0].skills[0],{element:0,range:'Pound'}).range"),'Pound');
assert.throws(()=>run("validateBattleSpec({...own[0],skills:[own[0].skills[0],own[0].skills[0]]})"));
assert.throws(()=>run("validateBattleSpec({...own[0],skills:[...own[0].skills,own[0].skills[0]]})"));
assert.throws(()=>run("validateBattleSpec({...own[0],script:'1,anything'})"));
run("let one=simulateTimedBattle(own,enemy,{trials:20,seed:7,timeLimit:20},{water:true},true);let again=simulateTimedBattle(own,enemy,{trials:20,seed:7,timeLimit:20},{water:true},true);");
assert.equal(run('JSON.stringify(one)'),run('JSON.stringify(again)'));
assert.equal(run('one.wins+one.losses+one.draws+one.timeouts'),20);
assert(run('one.trace.length>0'));
assert(run('one.own.every(m=>m.traitExtra<=m.damage+1e-8)'));
run("let dry=simulateTimedBattle([testSpec('Scorchhowl')],enemy,{trials:20,timeLimit:10,epStart:0,epRegen:0,ultGain:0});");
assert.equal(run("dry.own[0].actions['burn-breaker']?.casts||0"),0);
assert.equal(run("dry.own[0].actions['falling-star']?.casts||0"),0);
run("let slow=testSpec('Scorchhowl');slow.skills=slow.skills.map(s=>({...s,cooldown:120}));let slowResult=simulateTimedBattle([slow],[{...enemy[0],hp:50000}],{trials:20,timeLimit:10,epRegen:20});");
assert(run('slowResult.own[0].cooldownWait>0'));
assert(run("Object.values(slowResult.own[0].actions).filter(a=>a.name!=='ATK').every(a=>a.casts<=20)"));
run("let scripted=testSpec('Scorchhowl');scripted.script='B,1,B,2,U';let sequence=simulateTimedBattle([scripted],[{...enemy[0],hp:50000}],{trials:20,timeLimit:10}, {},true);");
assert(run("sequence.trace.some(e=>e.text.includes('ATK'))"));
run("let optimized=optimizeBattleLoadouts([testSpec('Glacy')],enemy,{trials:20,timeLimit:12,seed:3},{water:true});");
assert(run('optimized.evaluations>0'));
assert(run('optimized.selected[0].skills.length===2'));
assert(run('compareBattleResults(optimized.result,optimized.baseline)<=0'));
const worker=fs.readFileSync(new URL('../dist/simulation.worker.js',import.meta.url),'utf8');
const messages=[];
const wc=vm.createContext({self:{postMessage:m=>messages.push(m)}});
vm.runInContext(worker,wc);
wc.input={own:run('own'),enemy:run('enemy'),settings:{trials:20,timeLimit:10},traits:{}};
vm.runInContext('self.onmessage({data:input})',wc);
assert.equal(messages.at(-1).result.trials,20);
const bundle=fs.readFileSync(new URL('../dist/team.bundle.js',import.meta.url),'utf8');
const {version}=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8'));
assert(bundle.includes('simulation.worker.js?v='+version));assert(!bundle.includes('{{APP_VERSION}}'));
assert(bundle.includes('not your real chance of winning'));
console.log('PASS: timed attacks, two-skill constraint, energy/cooldown/ultimate gates, scripts, deterministic trials, metrics, independent loadout validation and worker execution.');
