let visibleMatches=[],activeMatch=-1,profileKey='';
function hideMatches(){visibleMatches=[];activeMatch=-1;$('searchResults').innerHTML='';$('enemySearch').setAttribute('aria-expanded','false');$('enemySearch').removeAttribute('aria-activedescendant')}
function highlightMatch(){const buttons=$('searchResults').querySelectorAll('button');buttons.forEach((b,i)=>b.setAttribute('aria-selected',i===activeMatch));if(activeMatch>=0){$('enemySearch').setAttribute('aria-activedescendant',`match-${visibleMatches[activeMatch].id}`);buttons[activeMatch]?.scrollIntoView({block:'nearest'})}else $('enemySearch').removeAttribute('aria-activedescendant')}
function showNameMatches(){const query=$('enemySearch').value;if(!query.trim()){if(namedEnemy)clearNamedEnemy();else hideMatches();return}const matches=searchDex(query);activeMatch=-1;visibleMatches=matches.slice(0,8);$('enemySearch').removeAttribute('aria-activedescendant');$('enemySearch').setAttribute('aria-expanded',!!matches.length);if(!matches.length){$('searchResults').innerHTML='<p class="hint" role="status">No match in the checked index. Try another spelling or choose elements below.</p>';return}$('searchResults').innerHTML=visibleMatches.map(a=>`<button class="nameMatch" type="button" role="option" aria-selected="false" id="match-${a.id}" data-id="${a.id}"><strong>${a.name}</strong><span>${a.forms.length} form${a.forms.length===1?'':'s'}${a.forms.some(f=>f.key==='prismana-form')?' · ◇ Prismana':''} · #${a.id}</span></button>`).join('')+(matches.length>8?`<p class="hint">${matches.length} matches. Keep typing to narrow the list.</p>`:'')}
function selectEnemy(id){const a=dexById.get(id);if(!a)return;namedEnemy=a;$('enemySearch').value=a.name;hideMatches();$('enemyForm').innerHTML=a.forms.map(f=>`<option value="${f.key}">${f.label} · ${f.elements.map(e=>types[e]).join(" + ")}</option>`).join('');$('enemyForm').disabled=false;$('elementEditor').open=false;applyNamedForm(a.forms[0].key);$('enemyForm').focus({preventScroll:true})}
function applyNamedForm(key){if(!namedEnemy)return;const f=namedEnemy.forms.find(x=>x.key===key);if(!f)return;$('enemyForm').value=key;selected=[...f.elements];prismatic=key==='prismana-form';spatial='Unknown';render()}
function syncEnemyProfile(){if(!namedEnemy){$('normal').disabled=false;$('prism').disabled=false;return}const f=namedEnemy.forms.find(x=>x.key===$('enemyForm').value)||namedEnemy.forms[0];$('normal').disabled=!namedEnemy.forms.some(x=>x.key==='basic-form');$('prism').disabled=!namedEnemy.forms.some(x=>x.key==='prismana-form');const key=namedEnemy.id+'|'+f.key;if(profileKey===key)return;profileKey=key;$('enemyDetails').innerHTML=`<div class="factors">${f.elements.map(e=>`<span class="factor" style="color:${colors[e]}">${types[e]}</span>`).join('')}<a href="${f.source}" target="_blank" rel="noopener">Official form</a></div><p class="hint">${f.spatial==='Tunnel'?'Can tunnel. Choose Tunnel below only while underground.':f.spatial==='Fly'?'Has a flying combat skill. Choose Fly below only while airborne.':'Set the active Spatial state if known.'}</p>${namedEnemy.forms.length===1?`<p class="hint">${f.key==='prismana-form'?'Only Prismana is published for this entry.':'No Prismana form listed in the checked official Wiki.'}</p>`:''}`}
function clearNamedEnemy(rerender=true){namedEnemy=null;profileKey='';$('enemySearch').value='';hideMatches();$('enemyDetails').innerHTML='';$('enemyForm').innerHTML='<option>Select an Aniimo first</option>';$('enemyForm').disabled=true;$('normal').disabled=false;$('prism').disabled=false;$('elementEditor').open=true;if(rerender)render()}
$('enemySearch').addEventListener('input',showNameMatches);
$('enemySearch').addEventListener('keydown',e=>{if(e.key==='Escape'){hideMatches();return}if(e.key==='ArrowDown'||e.key==='ArrowUp'){if(!visibleMatches.length)showNameMatches();if(!visibleMatches.length)return;e.preventDefault();activeMatch=e.key==='ArrowDown'?(activeMatch+1)%visibleMatches.length:(activeMatch<=0?visibleMatches.length-1:activeMatch-1);highlightMatch();return}if(e.key==='Enter'){const matches=searchDex($('enemySearch').value);const chosen=activeMatch>=0?visibleMatches[activeMatch]:matches[0];if(chosen){e.preventDefault();selectEnemy(chosen.id)}}});
$('searchResults').addEventListener('click',e=>{const b=e.target.closest('button[data-id]');if(b)selectEnemy(b.dataset.id)});
$('enemyForm').addEventListener('change',()=>applyNamedForm($('enemyForm').value));
$('clearEnemy').onclick=()=>{clearNamedEnemy();$('enemySearch').focus()};
$('moreCounterDetails').addEventListener('toggle',()=>{if($('moreCounterDetails').open)renderMoreRecommendations()});
document.addEventListener('click',e=>{if(!e.target.closest('.enemylookup'))hideMatches()});
render();
