// Form/skill facts: current official Aniimo Wiki, checked 2026-09-30.
// Pound tags use MetaBot's skill reference; no Spatial damage multiplier assumed.
const move=(name,element,range='Ground',community=false)=>({name,element,range,community});
const entry=(name,id,form,elements,atk,role,moves,mobility='',note='')=>({name,form,elements,atk,role,moves,mobility,note,source:`https://wiki.aniimo.com/item/${id}/${form}`});
const roster=[
entry('Irisalis','10001','prismana-form',[2],130,'DPS',[move('ATK',2,'Ranged')],'','Grass distance attacks; its clone mechanics reward coordinated skill and basic attack use.'),
entry('Grizbo','069','basic-form',[5],124,'DPS',[move('ATK',5)],'','Earth damage with an ATK-speed boost during its Enraged state.'),
entry('Sherro','055','basic-form',[1],121,'DPS',[move('Flowing Water Slash',1),move('Torrent Slam',1,'Pound',true)],'','Water terrain or absorbed water supports its Water damage trait.'),
entry('Scorchhowl','003','basic-form',[0],119,'DPS',[move('Fire Kick',0,'Pound',true)],'','Its trait rewards attacks against elementally countered targets.'),
entry('Infergon','067','basic-form',[0],125,'DPS',[move('ATK',0,'Ranged')],'Fly','Hot Breath attacks from the air; its trait rewards Fire Debuff setup.'),
entry('Thornblade','034','basic-form',[2],121,'DPS',[move('Thorny Rain',2)],'','Skill use builds Sword Dance stacks for stronger basic attacks.'),
entry('Fulmintis','10003','basic-form',[3],130,'DPS',[move('Lightning Rush',3)],'','Lightning Rush is a close-range attack. Exploration flight is not counted as combat flight.'),
entry('Fenmane','060','basic-form',[3],125,'DPS',[move('ATK',3,'Ranged')],'','Official basic attack description confirms distance attacks.'),
entry('Stellarys','006','basic-form',[8],125,'DPS',[move('ATK',8,'Ranged')],'Fly','Shooting Star Glide enables attacks while flying.'),
entry('Cornet','009','beach-form',[6,1],121,'DPS',[move('ATK',6,'Ranged'),move('Water Tornado',1)],'Fly','Use Take Off or its flying skill state for ground-attack evasion.'),
entry('Glynsera','044','prismana-form',[7,4],118,'DPS',[move('Ice Strikes',4),move('Prismana Slash',7)],'','Prismana Slash is explicitly described as firing Light blades. Its ranged counter tag is not assumed.'),
entry('Glynsera','044','nighttime-form',[8,4],118,'DPS',[move('Ice Strikes',4),move('Night Slash',8)],'','Night Slash is described as using Dark blades.'),
entry('Minespine','074','basic-form',[5],90,'BREAK',[move('ATK',5)],'Tunnel','Tunnel avoids ranged attacks while consuming stamina; Pound can launch it out.'),
entry('Panpanta','052','basic-form',[1],85,'BREAK',[move('ATK',1)],'','Water Break option; its trait benefits from an opposite-sex Susuta-family teammate.'),
entry('Glacy','015','basic-form',[1,4],95,'Heal',[move('ATK',1,'Ranged'),move('Ice Orb',4,'Ranged')],'','A healing option with a targeted Ice Orb that can freeze enemies.'),
entry('Sherro','055','prismana-form',[7,1],121,'DPS',[move('Flowing Water Slash',1),move('Torrent Slam',1,'Pound',true)],'','Light is a form element; this recommendation scores only its verified Water attack.'),
entry('Thornblade','034','prismana-form',[2,1],121,'DPS',[move('Thorny Rain',2)],'','Water is a form element; this recommendation scores its verified Grass attack.')
];
function spatialFit(a,m){if(spatial==='Tunnel')return m.range==='Pound'?2:m.range==='Ranged'?-2:0;if(spatial==='Fly')return m.range==='Ranged'?1:0;if(spatial==='Ranged')return a.mobility==='Tunnel'?1:0;if(spatial==='Pound')return a.mobility==='Fly'?1:0;return 0}
function comparePicks(a,b){return b.space-a.space||($('estimate').checked?b.product-a.product:b.strong-a.strong||a.weak-b.weak)||(b.a.role==='DPS')-(a.a.role==='DPS')||a.incomingWeak-b.incomingWeak||b.incomingResist-a.incomingResist||b.a.atk-a.a.atk||a.a.name.localeCompare(b.a.name)||a.a.form.localeCompare(b.a.form)}
const recommendationCache=new Map();
function getRecommendations(){if(!selected.length)return[];const key=selected.join(',')+'|'+spatial+'|'+$('estimate').checked;if(recommendationCache.has(key))return recommendationCache.get(key);const result=roster.map(a=>{const moves=a.moves.map(m=>{const factors=selected.map(d=>matrix[m.element][d]);return{a,m,factors,space:spatialFit(a,m),product:factors.reduce((x,y)=>x*y,1),strong:factors.filter(v=>v>1).length,weak:factors.filter(v=>v<1).length,incomingWeak:selected.reduce((n,d)=>n+a.elements.filter(e=>matrix[d][e]>1).length,0),incomingResist:selected.reduce((n,d)=>n+a.elements.filter(e=>matrix[d][e]<1).length,0)}});return moves.sort(comparePicks)[0]}).filter(r=>r.space>=0).sort(comparePicks);if(recommendationCache.size>=64)recommendationCache.delete(recommendationCache.keys().next().value);recommendationCache.set(key,result);return result}
function formName(s){return s==='basic-form'?'Standard':s==='prismana-form'?'Prismatic':s==='beach-form'?'Beach':'Nighttime'}
function pickCard(r,i){const a=r.a;let movement=spatial==='Unknown'?'Select the enemy’s Spatial state to check reach.':r.space>0?spatial==='Tunnel'?`Use ${r.m.name} to interrupt Tunnel. Pound tag: community reference.`:spatial==='Fly'?'Distance attack option against airborne enemies.':spatial==='Ranged'?'Use Tunnel to avoid ranged attacks while stamina lasts.':'Use its flying combat state to evade ground attacks.':'No confirmed Spatial advantage for this listed move.';return `<article class="pick"><div class="picktop"><div><span class="pickrank">${String(i+1).padStart(2,'0')}</span><strong>${a.name}</strong><span class="formtag">${formName(a.form)}</span></div><span class="role">${a.role}</span></div><div class="pickmeta">${a.elements.map(e=>`<span style="color:${colors[e]}">${types[e]}</span>`).join(' + ')}<span>Base ATK ${a.atk}</span></div><p class="pickmove">Use <strong>${r.m.name}</strong> · ${types[r.m.element]}${r.m.community?' · Pound tag (community)':''}</p><div class="factors">${selected.map((d,j)=>`<span class="factor ${cls(r.factors[j])}">vs ${types[d]} ×${fmt(r.factors[j])}</span>`).join('')}${$('estimate').checked?`<span class="factor">≈ ×${fmt(r.product)} combined</span>`:''}</div>${spatial==='Unknown'?'':`<p class="pickspatial">${movement}</p>`}<details class="pickDetails"><summary>Why this pick</summary><p class="hint">${a.note}</p><div class="pickbottom"><span class="hint">${r.incomingWeak} incoming weakness pair${r.incomingWeak===1?'':'s'} · enemy-element attacks only</span><a href="${a.source}" target="_blank" rel="noopener">Official form & skills</a></div></details></article>`}
function renderMoreRecommendations(){const rs=getRecommendations();$('morePicks').innerHTML=rs.slice(3).map((r,i)=>pickCard(r,i+3)).join('')}
function renderRecommendations(){const rs=getRecommendations();$('aniimoPicks').innerHTML=rs.length?rs.slice(0,3).map(pickCard).join(''):'<p class="hint">Select at least one enemy element to see recommended Aniimo.</p>';if($('moreCounterDetails').open)renderMoreRecommendations();else $('morePicks').innerHTML=''}
