const battleSkillCatalog=[
  {
    "name": "Irisalis",
    "skills": [
      {
        "name": "Whirling Blossom Rain",
        "kind": "skill",
        "element": 2,
        "power": 60,
        "breakPower": 0,
        "cooldown": null,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/irisalis",
        "official": "https://wiki.aniimo.com/item/10001/prismana-form",
        "key": "whirling-blossom-rain",
        "effect": {
          "cloneBeam": true
        },
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Unknown cooldown; model input required"
      },
      {
        "name": "Irisalis Shadow",
        "kind": "skill",
        "element": 2,
        "power": 90,
        "breakPower": 0,
        "cooldown": null,
        "cost": 40,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/irisalis",
        "official": "https://wiki.aniimo.com/item/10001/prismana-form",
        "key": "irisalis-shadow",
        "effect": {
          "addClone": true,
          "duration": 30
        },
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 5,
        "timingStatus": "Unknown cooldown; model input required"
      },
      {
        "name": "Florae Descent",
        "kind": "ultimate",
        "element": 2,
        "power": 240,
        "breakPower": 0,
        "cooldown": null,
        "cost": 0,
        "ultimateCost": 100,
        "source": "https://aniimoguide.com/aniidex/irisalis",
        "official": "https://wiki.aniimo.com/item/10001/prismana-form",
        "key": "florae-descent",
        "effect": {
          "addClone": true,
          "duration": 30
        },
        "cast": 1.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 6,
        "timingStatus": "Unknown cooldown; model input required"
      },
      {
        "name": "ATK",
        "kind": "basic",
        "element": 2,
        "power": 6,
        "breakPower": 0,
        "cooldown": null,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/irisalis",
        "official": "https://wiki.aniimo.com/item/10001/prismana-form",
        "key": "atk",
        "effect": {},
        "cast": 0.5,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 1,
        "timingStatus": "Unknown cooldown; model input required"
      }
    ],
    "source": "https://aniimoguide.com/aniidex/irisalis"
  },
  {
    "name": "Grizbo",
    "skills": [
      {
        "name": "Claw of Madness",
        "kind": "skill",
        "element": 8,
        "power": 30,
        "breakPower": 10,
        "cooldown": null,
        "cost": 10,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/grizbo",
        "official": "https://wiki.aniimo.com/item/069/basic-form",
        "key": "claw-of-madness",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": "prismana-form",
        "weight": 3,
        "timingStatus": "Unknown cooldown; model input required"
      },
      {
        "name": "Fanatic Clawing",
        "kind": "skill",
        "element": 5,
        "power": 30,
        "breakPower": 10,
        "cooldown": null,
        "cost": 10,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/grizbo",
        "official": "https://wiki.aniimo.com/item/069/basic-form",
        "key": "fanatic-clawing",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Unknown cooldown; model input required"
      },
      {
        "name": "Earthquake",
        "kind": "skill",
        "element": 5,
        "power": 38,
        "breakPower": 12.7,
        "cooldown": 10,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/grizbo",
        "official": "https://wiki.aniimo.com/item/069/basic-form",
        "key": "earthquake",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Critical Hit",
        "kind": "skill",
        "element": 5,
        "power": 90,
        "breakPower": 30,
        "cooldown": 1,
        "cost": 30,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/grizbo",
        "official": "https://wiki.aniimo.com/item/069/basic-form",
        "key": "critical-hit",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Rock Smash",
        "kind": "ultimate",
        "element": 5,
        "power": 260,
        "breakPower": 86.7,
        "cooldown": 8,
        "cost": 0,
        "ultimateCost": 200,
        "source": "https://aniimoguide.com/aniidex/grizbo",
        "official": "https://wiki.aniimo.com/item/069/basic-form",
        "key": "rock-smash",
        "effect": {
          "enrage": true
        },
        "cast": 1.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 6,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "ATK",
        "kind": "basic",
        "element": 5,
        "power": 6,
        "breakPower": 1.6,
        "cooldown": 0.1,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/grizbo",
        "official": "https://wiki.aniimo.com/item/069/basic-form",
        "key": "atk",
        "effect": {},
        "cast": 0.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 1,
        "timingStatus": "Community timing reference; live patch unverified"
      }
    ],
    "source": "https://aniimoguide.com/aniidex/grizbo"
  },
  {
    "name": "Sherro",
    "skills": [
      {
        "name": "Flowing Water Slash",
        "kind": "skill",
        "element": 1,
        "power": 70,
        "breakPower": 23.3,
        "cooldown": 5,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/sherro",
        "official": "https://wiki.aniimo.com/item/055/basic-form",
        "key": "flowing-water-slash",
        "effect": {
          "waterBonus": 0.3
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Prismana Slam",
        "kind": "skill",
        "element": 7,
        "power": 47,
        "breakPower": 23.5,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/sherro",
        "official": "https://wiki.aniimo.com/item/055/basic-form",
        "key": "prismana-slam",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": "prismana-form",
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Torrent Slam",
        "kind": "skill",
        "element": 1,
        "power": 47,
        "breakPower": 23.5,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/sherro",
        "official": "https://wiki.aniimo.com/item/055/basic-form",
        "key": "torrent-slam",
        "effect": {
          "waterBonus": 0.3,
          "waterBuff": 0.15,
          "duration": 20
        },
        "cast": 1,
        "hits": 1,
        "range": "Pound",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Thunder Slam",
        "kind": "skill",
        "element": 3,
        "power": 47,
        "breakPower": 23.5,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/sherro",
        "official": "https://wiki.aniimo.com/item/055/basic-form",
        "key": "thunder-slam",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": "thunderstorm-form",
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Hydro Roll",
        "kind": "skill",
        "element": 1,
        "power": 83,
        "breakPower": 41.5,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/sherro",
        "official": "https://wiki.aniimo.com/item/055/basic-form",
        "key": "hydro-roll",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "ATK",
        "kind": "basic",
        "element": 1,
        "power": 6,
        "breakPower": 1.6,
        "cooldown": 0.1,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/sherro",
        "official": "https://wiki.aniimo.com/item/055/basic-form",
        "key": "atk",
        "effect": {},
        "cast": 0.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 1,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Torrent Blade",
        "kind": "ultimate",
        "element": 1,
        "power": 160,
        "breakPower": 80,
        "cooldown": 8,
        "cost": 0,
        "ultimateCost": 100,
        "source": "https://aniimoguide.com/aniidex/sherro",
        "official": "https://wiki.aniimo.com/item/055/basic-form",
        "key": "torrent-blade",
        "effect": {},
        "cast": 1.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 6,
        "timingStatus": "Community timing reference; live patch unverified"
      }
    ],
    "source": "https://aniimoguide.com/aniidex/sherro"
  },
  {
    "name": "Scorchhowl",
    "skills": [
      {
        "name": "Fire Kick",
        "kind": "skill",
        "element": 0,
        "power": 72,
        "breakPower": 24,
        "cooldown": 15,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/scorchhowl",
        "official": "https://wiki.aniimo.com/item/003/basic-form",
        "key": "fire-kick",
        "effect": {
          "dodge": true
        },
        "cast": 1,
        "hits": 1,
        "range": "Pound",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Pebble Kick",
        "kind": "skill",
        "element": 5,
        "power": 40,
        "breakPower": 13.3,
        "cooldown": 15,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/scorchhowl",
        "official": "https://wiki.aniimo.com/item/003/basic-form",
        "key": "pebble-kick",
        "effect": {
          "dodge": true
        },
        "cast": 1,
        "hits": 1,
        "range": "Pound",
        "variant": "highland-form",
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Burn Breaker",
        "kind": "skill",
        "element": 0,
        "power": 84,
        "breakPower": 42,
        "cooldown": 1,
        "cost": 30,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/scorchhowl",
        "official": "https://wiki.aniimo.com/item/003/basic-form",
        "key": "burn-breaker",
        "effect": {
          "charge": true
        },
        "cast": 2,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 5,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Lightning Kick",
        "kind": "skill",
        "element": 3,
        "power": 40,
        "breakPower": 13.3,
        "cooldown": 15,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/scorchhowl",
        "official": "https://wiki.aniimo.com/item/003/basic-form",
        "key": "lightning-kick",
        "effect": {
          "dodge": true,
          "control": 5
        },
        "cast": 1,
        "hits": 1,
        "range": "Pound",
        "variant": "thunderstorm-form",
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Fire Bolt",
        "kind": "skill",
        "element": 0,
        "power": 30,
        "breakPower": 10,
        "cooldown": 1,
        "cost": 10,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/scorchhowl",
        "official": "https://wiki.aniimo.com/item/003/basic-form",
        "key": "fire-bolt",
        "effect": {
          "fire": 2,
          "duration": 5
        },
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Falling Star",
        "kind": "ultimate",
        "element": 0,
        "power": 170,
        "breakPower": 56.7,
        "cooldown": 8,
        "cost": 0,
        "ultimateCost": 100,
        "source": "https://aniimoguide.com/aniidex/scorchhowl",
        "official": "https://wiki.aniimo.com/item/003/basic-form",
        "key": "falling-star",
        "effect": {},
        "cast": 1.5,
        "hits": 1,
        "range": "Pound",
        "variant": null,
        "weight": 6,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "ATK",
        "kind": "basic",
        "element": 0,
        "power": 6,
        "breakPower": 1.6,
        "cooldown": 0.1,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/scorchhowl",
        "official": "https://wiki.aniimo.com/item/003/basic-form",
        "key": "atk",
        "effect": {},
        "cast": 0.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 1,
        "timingStatus": "Community timing reference; live patch unverified"
      }
    ],
    "source": "https://aniimoguide.com/aniidex/scorchhowl"
  },
  {
    "name": "Infergon",
    "skills": [
      {
        "name": "Fiery Charge",
        "kind": "skill",
        "element": 0,
        "power": 60,
        "breakPower": 20,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/infergon",
        "official": "https://wiki.aniimo.com/item/067/basic-form",
        "key": "fiery-charge",
        "effect": {
          "shield": 0.05,
          "duration": 10
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Lava Breath",
        "kind": "skill",
        "element": 0,
        "power": 62,
        "breakPower": 31,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/infergon",
        "official": "https://wiki.aniimo.com/item/067/basic-form",
        "key": "lava-breath",
        "effect": {
          "fire": 8,
          "duration": 8
        },
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Flaming Claws",
        "kind": "skill",
        "element": 0,
        "power": 45,
        "breakPower": 15,
        "cooldown": 1,
        "cost": 15,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/infergon",
        "official": "https://wiki.aniimo.com/item/067/basic-form",
        "key": "flaming-claws",
        "effect": {
          "consumeFire": 2,
          "bonusMight": 30
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Hot Breath",
        "kind": "ultimate",
        "element": 0,
        "power": 168,
        "breakPower": 56,
        "cooldown": 8,
        "cost": 0,
        "ultimateCost": 100,
        "source": "https://aniimoguide.com/aniidex/infergon",
        "official": "https://wiki.aniimo.com/item/067/basic-form",
        "key": "hot-breath",
        "effect": {
          "fire": 8,
          "duration": 8
        },
        "cast": 1.5,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 6,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "ATK",
        "kind": "basic",
        "element": 0,
        "power": 6,
        "breakPower": 1.6,
        "cooldown": 0.1,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/infergon",
        "official": "https://wiki.aniimo.com/item/067/basic-form",
        "key": "atk",
        "effect": {},
        "cast": 0.5,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 1,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Gale Charge",
        "kind": "skill",
        "element": 6,
        "power": 60,
        "breakPower": 20,
        "cooldown": null,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/infergon",
        "official": "https://wiki.aniimo.com/item/067/basic-form",
        "key": "gale-charge",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": "prismana-form",
        "weight": 3,
        "timingStatus": "Unknown cooldown; model input required"
      }
    ],
    "source": "https://aniimoguide.com/aniidex/infergon"
  },
  {
    "name": "Thornblade",
    "skills": [
      {
        "name": "Thorny Defense",
        "kind": "skill",
        "element": 2,
        "power": 75,
        "breakPower": 33,
        "cooldown": 6,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/thornblade",
        "official": "https://wiki.aniimo.com/item/034/basic-form",
        "key": "thorny-defense",
        "effect": {
          "counter": true,
          "reduction": 0.2,
          "duration": 1
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Aqua Defense",
        "kind": "skill",
        "element": 1,
        "power": 75,
        "breakPower": 33,
        "cooldown": 15,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/thornblade",
        "official": "https://wiki.aniimo.com/item/034/basic-form",
        "key": "aqua-defense",
        "effect": {
          "counter": true,
          "reduction": 0.2,
          "duration": 1
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": "prismana-form",
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Thorny Impact",
        "kind": "skill",
        "element": 2,
        "power": 57,
        "breakPower": 20,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/thornblade",
        "official": "https://wiki.aniimo.com/item/034/basic-form",
        "key": "thorny-impact",
        "effect": {
          "critBuff": 0.15,
          "duration": 15
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 5,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Lightning Impact",
        "kind": "skill",
        "element": 3,
        "power": 57,
        "breakPower": 47,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/thornblade",
        "official": "https://wiki.aniimo.com/item/034/basic-form",
        "key": "lightning-impact",
        "effect": {
          "critBuff": 0.15,
          "duration": 15
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": "thunderstorm-form",
        "weight": 5,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Thorny Rain",
        "kind": "skill",
        "element": 2,
        "power": 30,
        "breakPower": 13.3,
        "cooldown": 1,
        "cost": 10,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/thornblade",
        "official": "https://wiki.aniimo.com/item/034/basic-form",
        "key": "thorny-rain",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Elegant Waltz",
        "kind": "ultimate",
        "element": 2,
        "power": 172,
        "breakPower": 43,
        "cooldown": 8,
        "cost": 0,
        "ultimateCost": 100,
        "source": "https://aniimoguide.com/aniidex/thornblade",
        "official": "https://wiki.aniimo.com/item/034/basic-form",
        "key": "elegant-waltz",
        "effect": {},
        "cast": 1.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 6,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "ATK",
        "kind": "basic",
        "element": 2,
        "power": 6,
        "breakPower": 1.6,
        "cooldown": 0.1,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/thornblade",
        "official": "https://wiki.aniimo.com/item/034/basic-form",
        "key": "atk",
        "effect": {},
        "cast": 0.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 1,
        "timingStatus": "Community timing reference; live patch unverified"
      }
    ],
    "source": "https://aniimoguide.com/aniidex/thornblade"
  },
  {
    "name": "Fulmintis",
    "skills": [
      {
        "name": "Lightning Rush",
        "kind": "skill",
        "element": 3,
        "power": 35,
        "breakPower": 5.8,
        "cooldown": 1,
        "cost": 10,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/fulmintis",
        "official": "https://wiki.aniimo.com/item/10003/basic-form",
        "key": "lightning-rush",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Lightning Blade Impact",
        "kind": "skill",
        "element": 3,
        "power": 45,
        "breakPower": 7.5,
        "cooldown": 15,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/fulmintis",
        "official": "https://wiki.aniimo.com/item/10003/basic-form",
        "key": "lightning-blade-impact",
        "effect": {
          "control": 6
        },
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Lightning Surge",
        "kind": "skill",
        "element": 3,
        "power": 0,
        "breakPower": 0,
        "cooldown": 18,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/fulmintis",
        "official": "https://wiki.aniimo.com/item/10003/basic-form",
        "key": "lightning-surge",
        "effect": {
          "critBuff": 0.35,
          "duration": 20
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 5,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Enhanced Light Blade",
        "kind": "skill",
        "element": 7,
        "power": 0,
        "breakPower": 0,
        "cooldown": 18,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/fulmintis",
        "official": "https://wiki.aniimo.com/item/10003/basic-form",
        "key": "enhanced-light-blade",
        "effect": {
          "critBuff": 0.35,
          "duration": 20
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": "prismana-form",
        "weight": 5,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "ATK",
        "kind": "basic",
        "element": 3,
        "power": 6,
        "breakPower": 1.6,
        "cooldown": 0.1,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/fulmintis",
        "official": "https://wiki.aniimo.com/item/10003/basic-form",
        "key": "atk",
        "effect": {},
        "cast": 0.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 1,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Thunder Lance",
        "kind": "ultimate",
        "element": 3,
        "power": 180,
        "breakPower": 60,
        "cooldown": 8,
        "cost": 0,
        "ultimateCost": 100,
        "source": "https://aniimoguide.com/aniidex/fulmintis",
        "official": "https://wiki.aniimo.com/item/10003/basic-form",
        "key": "thunder-lance",
        "effect": {
          "control": 3
        },
        "cast": 1.5,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 6,
        "timingStatus": "Community timing reference; live patch unverified"
      }
    ],
    "source": "https://aniimoguide.com/aniidex/fulmintis"
  },
  {
    "name": "Fenmane",
    "skills": [
      {
        "name": "Thunder Field",
        "kind": "skill",
        "element": 3,
        "power": 1,
        "breakPower": 0.2,
        "cooldown": 8,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/fenmane",
        "official": "https://wiki.aniimo.com/item/060/basic-form",
        "key": "thunder-field",
        "effect": {
          "field": 8
        },
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 5,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Lightning Dart",
        "kind": "skill",
        "element": 3,
        "power": 50,
        "breakPower": 8.3,
        "cooldown": 5,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/fenmane",
        "official": "https://wiki.aniimo.com/item/060/basic-form",
        "key": "lightning-dart",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Thunder Imprint",
        "kind": "skill",
        "element": 3,
        "power": 1,
        "breakPower": 0.2,
        "cooldown": 10,
        "cost": 30,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/fenmane",
        "official": "https://wiki.aniimo.com/item/060/basic-form",
        "key": "thunder-imprint",
        "effect": {
          "imprint": 8
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Radiant Dart",
        "kind": "skill",
        "element": 7,
        "power": 35,
        "breakPower": 5.8,
        "cooldown": 10,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/fenmane",
        "official": "https://wiki.aniimo.com/item/060/basic-form",
        "key": "radiant-dart",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": "prismana-form",
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "ATK",
        "kind": "basic",
        "element": 3,
        "power": 6,
        "breakPower": 0.8,
        "cooldown": 0.1,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/fenmane",
        "official": "https://wiki.aniimo.com/item/060/basic-form",
        "key": "atk",
        "effect": {},
        "cast": 0.5,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 1,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Thunderfeather Volley",
        "kind": "ultimate",
        "element": 3,
        "power": 100,
        "breakPower": 33.3,
        "cooldown": 8,
        "cost": 0,
        "ultimateCost": 100,
        "source": "https://aniimoguide.com/aniidex/fenmane",
        "official": "https://wiki.aniimo.com/item/060/basic-form",
        "key": "thunderfeather-volley",
        "effect": {},
        "cast": 1.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 6,
        "timingStatus": "Community timing reference; live patch unverified"
      }
    ],
    "source": "https://aniimoguide.com/aniidex/fenmane"
  },
  {
    "name": "Stellarys",
    "skills": [
      {
        "name": "Shadow Magic",
        "kind": "skill",
        "element": 8,
        "power": 0,
        "breakPower": 20,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/stellarys",
        "official": "https://wiki.aniimo.com/item/006/basic-form",
        "key": "shadow-magic",
        "effect": {
          "cloneBonus": 0.2,
          "duration": 20
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Chill Glide",
        "kind": "skill",
        "element": 4,
        "power": 74,
        "breakPower": 31,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/stellarys",
        "official": "https://wiki.aniimo.com/item/006/basic-form",
        "key": "chill-glide",
        "effect": {
          "ice": 1,
          "duration": 8
        },
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": "prismana-form",
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Shooting Star Glide",
        "kind": "skill",
        "element": 8,
        "power": 74,
        "breakPower": 31,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/stellarys",
        "official": "https://wiki.aniimo.com/item/006/basic-form",
        "key": "shooting-star-glide",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Starfall",
        "kind": "skill",
        "element": 8,
        "power": 40,
        "breakPower": 23.7,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/stellarys",
        "official": "https://wiki.aniimo.com/item/006/basic-form",
        "key": "starfall",
        "effect": {
          "damageBuff": 0.03,
          "duration": 20
        },
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Aquatic Glide",
        "kind": "skill",
        "element": 1,
        "power": 74,
        "breakPower": 31,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/stellarys",
        "official": "https://wiki.aniimo.com/item/006/basic-form",
        "key": "aquatic-glide",
        "effect": {
          "drainEp": 3
        },
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": "rainstorm-form",
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Comet Aureus",
        "kind": "ultimate",
        "element": 8,
        "power": 166,
        "breakPower": 55.3,
        "cooldown": 8,
        "cost": 0,
        "ultimateCost": 100,
        "source": "https://aniimoguide.com/aniidex/stellarys",
        "official": "https://wiki.aniimo.com/item/006/basic-form",
        "key": "comet-aureus",
        "effect": {},
        "cast": 1.5,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 6,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "ATK",
        "kind": "basic",
        "element": 8,
        "power": 6,
        "breakPower": 0.8,
        "cooldown": 0.1,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/stellarys",
        "official": "https://wiki.aniimo.com/item/006/basic-form",
        "key": "atk",
        "effect": {},
        "cast": 0.5,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 1,
        "timingStatus": "Community timing reference; live patch unverified"
      }
    ],
    "source": "https://aniimoguide.com/aniidex/stellarys"
  },
  {
    "name": "Cornet",
    "skills": [
      {
        "name": "Lightning Splitter",
        "kind": "skill",
        "element": 3,
        "power": 30,
        "breakPower": 5,
        "cooldown": 15,
        "cost": 10,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/cornet",
        "official": "https://wiki.aniimo.com/item/009/beach-form",
        "key": "lightning-splitter",
        "effect": {
          "control": 5
        },
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": "prismana-form",
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Wind Bomb Rush",
        "kind": "skill",
        "element": 6,
        "power": 157,
        "breakPower": 52.3,
        "cooldown": 1,
        "cost": 45,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/cornet",
        "official": "https://wiki.aniimo.com/item/009/beach-form",
        "key": "wind-bomb-rush",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Tornado",
        "kind": "skill",
        "element": 6,
        "power": 59,
        "breakPower": 9.8,
        "cooldown": 15,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/cornet",
        "official": "https://wiki.aniimo.com/item/009/beach-form",
        "key": "tornado",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Scream Splitter",
        "kind": "skill",
        "element": 6,
        "power": 30,
        "breakPower": 5,
        "cooldown": 1,
        "cost": 10,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/cornet",
        "official": "https://wiki.aniimo.com/item/009/beach-form",
        "key": "scream-splitter",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Water Tornado",
        "kind": "skill",
        "element": 1,
        "power": 45,
        "breakPower": 7.5,
        "cooldown": 15,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/cornet",
        "official": "https://wiki.aniimo.com/item/009/beach-form",
        "key": "water-tornado",
        "effect": {
          "drainEp": 4
        },
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": "beach-form",
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Leaf Tornado",
        "kind": "skill",
        "element": 2,
        "power": 45,
        "breakPower": 7.5,
        "cooldown": 15,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/cornet",
        "official": "https://wiki.aniimo.com/item/009/beach-form",
        "key": "leaf-tornado",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": "highland-form",
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "ATK",
        "kind": "basic",
        "element": 6,
        "power": 6,
        "breakPower": 0.8,
        "cooldown": 0.1,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/cornet",
        "official": "https://wiki.aniimo.com/item/009/beach-form",
        "key": "atk",
        "effect": {},
        "cast": 0.5,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 1,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Avian Harmony Ensemble",
        "kind": "ultimate",
        "element": 6,
        "power": 179,
        "breakPower": 29.8,
        "cooldown": 8,
        "cost": 0,
        "ultimateCost": 100,
        "source": "https://aniimoguide.com/aniidex/cornet",
        "official": "https://wiki.aniimo.com/item/009/beach-form",
        "key": "avian-harmony-ensemble",
        "effect": {},
        "cast": 1.5,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 6,
        "timingStatus": "Community timing reference; live patch unverified"
      }
    ],
    "source": "https://aniimoguide.com/aniidex/cornet"
  },
  {
    "name": "Glynsera",
    "skills": [
      {
        "name": "Frost Tail Strike",
        "kind": "skill",
        "element": 4,
        "power": 60,
        "breakPower": 20,
        "cooldown": 1,
        "cost": 15,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/glynsera",
        "official": "https://wiki.aniimo.com/item/044/prismana-form",
        "key": "frost-tail-strike",
        "effect": {
          "consumeIce": 10,
          "damageBonus": 0.85
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Boomerang Blade",
        "kind": "skill",
        "element": 4,
        "power": 39,
        "breakPower": 13,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/glynsera",
        "official": "https://wiki.aniimo.com/item/044/prismana-form",
        "key": "boomerang-blade",
        "effect": {
          "ice": 1,
          "duration": 8
        },
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Prismana Slash",
        "kind": "skill",
        "element": 7,
        "power": 55,
        "breakPower": 18.3,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/glynsera",
        "official": "https://wiki.aniimo.com/item/044/prismana-form",
        "key": "prismana-slash",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": "prismana-form",
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Ice Strikes",
        "kind": "skill",
        "element": 4,
        "power": 55,
        "breakPower": 18.3,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/glynsera",
        "official": "https://wiki.aniimo.com/item/044/prismana-form",
        "key": "ice-strikes",
        "effect": {
          "ice": 5,
          "duration": 8
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Night Slash",
        "kind": "skill",
        "element": 8,
        "power": 55,
        "breakPower": 18.3,
        "cooldown": 15,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/glynsera",
        "official": "https://wiki.aniimo.com/item/044/prismana-form",
        "key": "night-slash",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": "nighttime-form",
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Ice Tornado",
        "kind": "ultimate",
        "element": 4,
        "power": 155,
        "breakPower": 51.7,
        "cooldown": 8,
        "cost": 0,
        "ultimateCost": 100,
        "source": "https://aniimoguide.com/aniidex/glynsera",
        "official": "https://wiki.aniimo.com/item/044/prismana-form",
        "key": "ice-tornado",
        "effect": {},
        "cast": 1.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 6,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "ATK",
        "kind": "basic",
        "element": 4,
        "power": 6,
        "breakPower": 1.6,
        "cooldown": 0.1,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/glynsera",
        "official": "https://wiki.aniimo.com/item/044/prismana-form",
        "key": "atk",
        "effect": {},
        "cast": 0.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 1,
        "timingStatus": "Community timing reference; live patch unverified"
      }
    ],
    "source": "https://aniimoguide.com/aniidex/glynsera"
  },
  {
    "name": "Minespine",
    "skills": [
      {
        "name": "Earth Spikes",
        "kind": "skill",
        "element": 5,
        "power": 62,
        "breakPower": 20.7,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/minespine",
        "official": "https://wiki.aniimo.com/item/074/basic-form",
        "key": "earth-spikes",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Seismic Wave",
        "kind": "skill",
        "element": 5,
        "power": 120,
        "breakPower": 60,
        "cooldown": 1,
        "cost": 40,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/minespine",
        "official": "https://wiki.aniimo.com/item/074/basic-form",
        "key": "seismic-wave",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Stone Shell",
        "kind": "skill",
        "element": 5,
        "power": 30,
        "breakPower": 10,
        "cooldown": 1,
        "cost": 10,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/minespine",
        "official": "https://wiki.aniimo.com/item/074/basic-form",
        "key": "stone-shell",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Meteors",
        "kind": "ultimate",
        "element": 5,
        "power": 175,
        "breakPower": 58.3,
        "cooldown": 8,
        "cost": 0,
        "ultimateCost": 100,
        "source": "https://aniimoguide.com/aniidex/minespine",
        "official": "https://wiki.aniimo.com/item/074/basic-form",
        "key": "meteors",
        "effect": {},
        "cast": 1.5,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 6,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "ATK",
        "kind": "basic",
        "element": 5,
        "power": 6,
        "breakPower": 1.6,
        "cooldown": 0.1,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/minespine",
        "official": "https://wiki.aniimo.com/item/074/basic-form",
        "key": "atk",
        "effect": {},
        "cast": 0.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 1,
        "timingStatus": "Community timing reference; live patch unverified"
      }
    ],
    "source": "https://aniimoguide.com/aniidex/minespine"
  },
  {
    "name": "Panpanta",
    "skills": [
      {
        "name": "Water Cannon",
        "kind": "skill",
        "element": 1,
        "power": 65,
        "breakPower": 32.5,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/panpanta",
        "official": "https://wiki.aniimo.com/item/052/basic-form",
        "key": "water-cannon",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Water Cannonade",
        "kind": "skill",
        "element": 1,
        "power": 40,
        "breakPower": 20,
        "cooldown": 1,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/panpanta",
        "official": "https://wiki.aniimo.com/item/052/basic-form",
        "key": "water-cannonade",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": "prismana-form",
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Hydro Roll",
        "kind": "skill",
        "element": 1,
        "power": 18,
        "breakPower": 7.2,
        "cooldown": 1,
        "cost": 30,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/panpanta",
        "official": "https://wiki.aniimo.com/item/052/basic-form",
        "key": "hydro-roll",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Splash Shield",
        "kind": "skill",
        "element": 1,
        "power": 30,
        "breakPower": 12,
        "cooldown": 15,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/panpanta",
        "official": "https://wiki.aniimo.com/item/052/basic-form",
        "key": "splash-shield",
        "effect": {
          "shield": 0.08,
          "duration": 15
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Home Run",
        "kind": "ultimate",
        "element": 1,
        "power": 176,
        "breakPower": 88,
        "cooldown": 8,
        "cost": 0,
        "ultimateCost": 100,
        "source": "https://aniimoguide.com/aniidex/panpanta",
        "official": "https://wiki.aniimo.com/item/052/basic-form",
        "key": "home-run",
        "effect": {},
        "cast": 1.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 6,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "ATK",
        "kind": "basic",
        "element": 1,
        "power": 6,
        "breakPower": 1.6,
        "cooldown": 0.1,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/panpanta",
        "official": "https://wiki.aniimo.com/item/052/basic-form",
        "key": "atk",
        "effect": {},
        "cast": 0.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 1,
        "timingStatus": "Community timing reference; live patch unverified"
      }
    ],
    "source": "https://aniimoguide.com/aniidex/panpanta"
  },
  {
    "name": "Glacy",
    "skills": [
      {
        "name": "Healing Water",
        "kind": "skill",
        "element": 1,
        "power": 0,
        "breakPower": 0,
        "cooldown": 20,
        "cost": 20,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/glacy",
        "official": "https://wiki.aniimo.com/item/015/basic-form",
        "key": "healing-water",
        "effect": {
          "heal": 0.08,
          "selfHot": 0.12,
          "hotDuration": 5
        },
        "cast": 1,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 7,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Ice Orb",
        "kind": "skill",
        "element": 4,
        "power": 20,
        "breakPower": 1.3,
        "cooldown": 12,
        "cost": 10,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/glacy",
        "official": "https://wiki.aniimo.com/item/015/basic-form",
        "key": "ice-orb",
        "effect": {
          "control": 2.5
        },
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Glimmer Shot",
        "kind": "skill",
        "element": 7,
        "power": 20,
        "breakPower": 3.3,
        "cooldown": 1,
        "cost": 10,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/glacy",
        "official": "https://wiki.aniimo.com/item/015/basic-form",
        "key": "glimmer-shot",
        "effect": {
          "teamBuff": 0.15,
          "duration": 20
        },
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": "prismana-form",
        "weight": 5,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Bubble Rush",
        "kind": "skill",
        "element": 1,
        "power": 32,
        "breakPower": 2.1,
        "cooldown": 1,
        "cost": 10,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/glacy",
        "official": "https://wiki.aniimo.com/item/015/basic-form",
        "key": "bubble-rush",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Water Orb",
        "kind": "skill",
        "element": 1,
        "power": 30,
        "breakPower": 10,
        "cooldown": 1,
        "cost": 10,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/glacy",
        "official": "https://wiki.aniimo.com/item/015/basic-form",
        "key": "water-orb",
        "effect": {},
        "cast": 1,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 3,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "ATK",
        "kind": "basic",
        "element": 1,
        "power": 6,
        "breakPower": 0.8,
        "cooldown": 0.1,
        "cost": 0,
        "ultimateCost": 0,
        "source": "https://aniimoguide.com/aniidex/glacy",
        "official": "https://wiki.aniimo.com/item/015/basic-form",
        "key": "atk",
        "effect": {},
        "cast": 0.5,
        "hits": 1,
        "range": "Ranged",
        "variant": null,
        "weight": 1,
        "timingStatus": "Community timing reference; live patch unverified"
      },
      {
        "name": "Spring of Life",
        "kind": "ultimate",
        "element": 1,
        "power": 0,
        "breakPower": 0,
        "cooldown": 8,
        "cost": 0,
        "ultimateCost": 100,
        "source": "https://aniimoguide.com/aniidex/glacy",
        "official": "https://wiki.aniimo.com/item/015/basic-form",
        "key": "spring-of-life",
        "effect": {
          "teamHot": 0.36,
          "hotDuration": 6
        },
        "cast": 1.5,
        "hits": 1,
        "range": "Ground",
        "variant": null,
        "weight": 6,
        "timingStatus": "Community timing reference; live patch unverified"
      }
    ],
    "source": "https://aniimoguide.com/aniidex/glacy"
  }
];
