const $=id=>document.getElementById(id);
let team=[],pendingEnemy=null,teamMatches=[],activeTeamMatch=-1,nextTeamId=1;
const teamStorageKey='aniimo-counter-enemy-team-v1';
function formOptions(a,key){return a.forms.map(f=>`<option value="${f.key}"${f.key===key?' selected':''}>${f.label} · ${f.elements.map(e=>types[e]).join(' + ')}</option>`).join('')}
function resolveEnemy(member){const a=dexById.get(member.id),f=a?.forms.find(f=>f.key===member.form);return f?{...member,name:a.name,label:f.label,elements:f.elements,source:f.source}:null}
function saveTeam(){try{localStorage.setItem(teamStorageKey,JSON.stringify(team))}catch{}}
function restoreTeam(){try{const saved=JSON.parse(localStorage.getItem(teamStorageKey)||'[]');if(Array.isArray(saved))team=saved.slice(0,64).filter(m=>m&&spatialTypes.includes(m.spatial)&&resolveEnemy(m)).map(m=>({id:m.id,form:m.form,spatial:m.spatial,uid:nextTeamId++}))}catch{} }
function hideTeamMatches(){teamMatches=[];activeTeamMatch=-1;$('teamSearchResults').innerHTML='';$('teamSearch').setAttribute('aria-expanded','false');$('teamSearch').removeAttribute('aria-activedescendant')}
function clearPendingEnemy(){pendingEnemy=null;$('teamSearch').value='';hideTeamMatches();$('addForm').innerHTML='<option>Select an Aniimo first</option>';$('addForm').disabled=true;$('addEnemy').disabled=true;$('addSpatial').value='Unknown'}
function selectTeamEnemy(id){const a=dexById.get(id);if(!a)return;pendingEnemy=a;$('teamSearch').value=a.name;hideTeamMatches();$('addForm').innerHTML=formOptions(a,a.forms[0].key);$('addForm').value=a.forms[0].key;$('addForm').disabled=false;$('addEnemy').disabled=false;$('addSpatial').value='Unknown';$('addForm').focus()}
function searchTeamEnemies(){pendingEnemy=null;$('addEnemy').disabled=true;$('addForm').disabled=true;const found=searchDex($('teamSearch').value);teamMatches=found.slice(0,8);activeTeamMatch=-1;$('teamSearch').removeAttribute('aria-activedescendant');$('teamSearch').setAttribute('aria-expanded',!!teamMatches.length);$('teamSearchResults').innerHTML=teamMatches.map(a=>`<button class="nameMatch" role="option" aria-selected="false" id="team-match-${a.id}" data-id="${a.id}"><strong>${a.name}</strong><span>${a.forms.length} forms · #${a.id}</span></button>`).join('')+(found.length>8?`<p class="hint">${found.length} matches. Keep typing.</p>`:!found.length&&$('teamSearch').value.trim()?'<p class="hint">No checked species matches. Try another spelling.</p>':'')}
function addTeamEnemy(){if(!pendingEnemy)return;const form=pendingEnemy.forms.find(f=>f.key===$('addForm').value);if(!form)return;team.push({uid:nextTeamId++,id:pendingEnemy.id,form:form.key,spatial:$('addSpatial').value});$('teamNotice').textContent=`Added ${pendingEnemy.name} · ${form.label}.`;saveTeam();renderTeam();clearPendingEnemy();$('teamSearch').focus()}
function counterFormLabel(a){return formLabels[a.form]||a.form}
function matchRow(m){return `<div class="teamMatch"><div><strong>${m.enemy.name}</strong><span class="hint">${m.enemy.label} · ${m.enemy.spatial}</span></div><span class="factor ${m.covered?'good':['Blocked','Resisted'].includes(m.status)?'bad':''}">${m.status}</span><p>Use ${m.m.name} · ${types[m.m.element]}${m.m.community?' · Pound tag (community)':''}</p><div class="factors">${m.enemy.elements.map((e,i)=>`<span class="factor ${cls(m.factors[i])}">vs ${types[e]} ×${fmt(m.factors[i])}</span>`).join('')}</div>${m.status==='Blocked'?'<p class="hint">This listed ranged move cannot hit the active Tunnel state.</p>':m.status==='Reach unconfirmed'?'<p class="hint">No confirmed distance attack is listed for this pick against Fly.</p>':''}</div>`}
function teamCounterCard(r,i){return `<article class="pick"><div class="picktop"><div><span class="pickrank">${String(i+1).padStart(2,'0')}</span><strong>${r.a.name}</strong><span class="formtag">${counterFormLabel(r.a)}</span></div><span class="role">${r.a.role}</span></div><p class="coverage"><strong>${r.covered} / ${team.length}</strong> enemies with element advantage</p><p class="hint">${r.blocked} blocked · ${r.uncertain} reach unconfirmed · ${r.resisted} resisted · ${r.mixed} mixed</p><details class="teamMatchDetails"><summary>Matchups against the full team</summary>${r.matches.map(matchRow).join('')}</details><div class="pickbottom"><a href="${r.a.source}" target="_blank" rel="noopener">Official counter form &amp; skills</a></div></article>`}
function renderTeam(){
  $('teamCount').textContent=`${team.length} ENEM${team.length===1?'Y':'IES'}`;
  $('clearTeam').disabled=!team.length;
  $('teamMembers').innerHTML=team.length?team.map((m,i)=>{const a=dexById.get(m.id);return `<article class="teamMember"><div class="picktop"><strong>${i+1}. ${a.name}</strong><button class="quiet" data-remove="${m.uid}" aria-label="Remove enemy ${i+1}: ${a.name}">Remove</button></div><label for="form-${m.uid}">Form &amp; types</label><select id="form-${m.uid}" data-member="${m.uid}" data-field="form">${formOptions(a,m.form)}</select><label for="state-${m.uid}">Active Spatial state</label><select id="state-${m.uid}" data-member="${m.uid}" data-field="spatial">${spatialTypes.map(s=>`<option${s===m.spatial?' selected':''}>${s}</option>`).join('')}</select></article>`}).join(''):'<p class="emptyTeam">Your enemy team is empty.</p>';
  const enemies=team.map(resolveEnemy),ranked=rankTeamCounters(enemies);
  if(!enemies.length){$('teamResults').innerHTML='<p class="emptyTeam">Add enemies to see counters for the full team.</p>';return;}
  const coverage=suggestCoverageCounters(ranked);
  const missing=enemies.filter((e,i)=>!coverage.covered.has(i));
  $('teamResults').innerHTML=`<section class="teamCoverage"><h3>Suggested coverage group</h3><p class="hint">Up to three complementary counter forms from the checked roster.</p>${coverage.selected.length?`<div class="coverageGroup">${coverage.selected.map(r=>`<span><strong>${r.a.name}</strong> · ${counterFormLabel(r.a)}</span>`).join('')}</div>`:'<p>No confirmed element-advantage coverage in this roster for the selected states.</p>'}<p><strong>${coverage.covered.size} / ${enemies.length}</strong> enemies covered by an advantage matchup.</p>${missing.length?`<p class="hint">Remaining: ${missing.map(e=>e.name+' ('+e.label+')').join(', ')}. Check the individual matchups below.</p>`:''}</section><div class="resultHead"><h3>Main counters for this team</h3><span class="badge">17 CHECKED FORMS</span></div><p class="hint">Ranked by coverage across all ${enemies.length} enemies. Expand each counter to see its move and factors against every member.</p>${ranked.slice(0,3).map(teamCounterCard).join('')}<details class="teamMore"><summary>More overall counters</summary>${ranked.slice(3,8).map((r,i)=>teamCounterCard(r,i+3)).join('')}</details><details class="teamMore"><summary>Best counter for each enemy</summary>${enemies.map((e,i)=>{const matches=ranked.map(r=>r.matches[i]).filter(m=>m.status!=='Blocked'&&m.status!=='Reach unconfirmed').sort((a,b)=>comparePicks(a,b));const best=matches[0];return `<article class="teamIndividual"><h3>${i+1}. ${e.name} · ${e.label}</h3>${best?`<p><strong>${best.a.name}</strong> · ${counterFormLabel(best.a)}</p>${matchRow(best)}`:'<p>No confirmed reachable move in the checked counter roster for this active state.</p>'}</article>`}).join('')}</details>`;
}
$('teamSearch').addEventListener('input',searchTeamEnemies);
$('teamSearch').addEventListener('keydown',e=>{if(e.key==='Escape'){hideTeamMatches();return}if(e.key==='ArrowDown'||e.key==='ArrowUp'){if(!teamMatches.length)searchTeamEnemies();if(!teamMatches.length)return;e.preventDefault();activeTeamMatch=e.key==='ArrowDown'?(activeTeamMatch+1)%teamMatches.length:(activeTeamMatch<=0?teamMatches.length-1:activeTeamMatch-1);$('teamSearchResults').querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-selected',i===activeTeamMatch));$('teamSearch').setAttribute('aria-activedescendant',`team-match-${teamMatches[activeTeamMatch].id}`);return}if(e.key==='Enter'){const chosen=activeTeamMatch>=0?teamMatches[activeTeamMatch]:searchDex($('teamSearch').value)[0];if(chosen){e.preventDefault();selectTeamEnemy(chosen.id)}}});
$('teamSearchResults').addEventListener('click',e=>{const b=e.target.closest('button[data-id]');if(b)selectTeamEnemy(b.dataset.id)});
$('addEnemy').onclick=addTeamEnemy;
$('addForm').addEventListener('change',()=>{$('addSpatial').value='Unknown'});
$('clearTeamSearch').onclick=()=>{clearPendingEnemy();$('teamSearch').focus()};
$('clearTeam').onclick=()=>{team=[];saveTeam();renderTeam();$('teamNotice').textContent='Enemy team cleared.'};
$('teamMembers').addEventListener('click',e=>{const b=e.target.closest('button[data-remove]');if(!b)return;team=team.filter(m=>m.uid!==Number(b.dataset.remove));saveTeam();renderTeam();$('teamNotice').textContent='Enemy removed.'});
$('teamMembers').addEventListener('change',e=>{const field=e.target.dataset.field,m=team.find(m=>m.uid===Number(e.target.dataset.member));if(!m)return;if(field==='form'&&dexById.get(m.id).forms.some(f=>f.key===e.target.value)){m.form=e.target.value;m.spatial='Unknown'}else if(field==='spatial'&&spatialTypes.includes(e.target.value))m.spatial=e.target.value;else return;saveTeam();renderTeam();$('teamNotice').textContent='Team counters updated.'});
document.addEventListener('click',e=>{if(!e.target.closest('.enemylookup'))hideTeamMatches()});
restoreTeam();renderTeam();
